
# [FN, MW, FT, WW, BS, photo]
# ["", "", "", "", ""]

class Dic():
    def __init__(self):
        self.dictionary = {
"M4A4 | Daybreak" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49440529", "-", "-", "-", "-", "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Daybreak%20%28Factory%20New%29?filter=M4A4-s"],
"M4A4 | Poseidon" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49431023", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49460236", "-", "-", "-", "https://steamcommunity.com/market/listings/730%7D/M4A4%20%7C%20Poseidon%20(Minimal%20Wear)"],
"M4A4 | The Coalition" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176262582", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176262571", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176262588", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176262560", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176262579", "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20The%20Coalition%20%28Field-Tested%29?l=russian"],
"M4A4 | Eye of Horus" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176369984", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176369981", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176369970", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176369987", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176369929", "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Eye%20of%20Horus%20(Factory%20New)?l=russian"],
"M4A4 | Radiation Hazard" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=1322215", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=1321906", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=1321608", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=1322012", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=1321624", "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Radiation%20Hazard%20%28Field-Tested%29"],

"AK-47 | Gold Arabesque" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263099", "-", "-", "-", "-", "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Gold%20Arabesque%20(Factory%20New)?ysclid=m5mx39q54819994224"],
"AK-47 | Wild Lotus" : ["-", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176096715", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097753", "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Wild%20Lotus%20%28Field-Tested%29?ysclid=m5mxco1uuh643518217"],
"AK-47 | Vulcan" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=8996750", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=8991744", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=8990337", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=8991010", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=8995733", "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Vulcan%20(Factory%20New)"],\
"AK-47 | X-Ray" : ["-", "-", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176209700", "-", "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20X-Ray%20(Well-Worn)"],
"AK-47 | Hydroponic" : ["-", "-", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49653167", "-", "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Hydroponic%20(Well-Worn)"],

"M4A1-S | Knight" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14953256", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14962998", "-", "-", "-", "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Knight%20(Factory%20New)"],
"M4A1-S | Welcome to the Jungle" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176224958", "-", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176209759", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176209543", "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Welcome%20to%20the%20Jungle%20(Factory%20New)"],
"M4A1-S | Imminent Danger" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263205", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263500", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263406", "-", "-", "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Imminent%20Danger%20(Factory%20New)"],
"M4A1-S | Blue Phosphor" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176209265", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176209481", "-", "-", "-", "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Blue%20Phosphor%20(Factory%20New)"],
"M4A1-S | Hot Rod" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49430996", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49473121", "-", "-", "-", "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Hot%20Rod%20(Factory%20New)"],

"AUG | Akihabara Accept" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49758611", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49430987", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49419468", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49524773", "https://steamcommunity.com/market/listings/730/AUG%20%7C%20Akihabara%20Accept%20(Factory%20New)"],
"AUG | Midnight Lily" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097431", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176096918", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176096800", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097622", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097822", "https://steamcommunity.com/market/listings/730/AUG%20%7C%20Midnight%20Lily%20(Factory%20New)"],
"AUG | Hot Rod" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=1321501", "-", "-", "-", "-", "https://steamcommunity.com/market/listings/730/AUG%20%7C%20Hot%20Rod%20(Factory%20New)"],
"AUG | Flame Jörmungandr" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176096854", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097244", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176096734", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097646", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176096712", "https://steamcommunity.com/market/listings/730/AUG%20%7C%20Flame%20Jörmungandr%20(Factory%20New)"],
"AUG | Lil' Pig" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176460942", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176460469", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176460717", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176461285", "-", "https://steamcommunity.com/market/listings/730/AUG%20%7C%20Lil'%20Pig%20(Factory%20New)"],

"AWP | Gungnir" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097606", "-", "-", "-", "-", "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Gungnir%20(Factory%20New)"],
"AWP | Dragon Lore" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14966470", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14977513", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14959400", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14980583", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=14963025", "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Dragon%20Lore%20(Factory%20New)"],
"AWP | Medusa" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49679904", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49638215", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49419414", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49440513", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49612094", "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Medusa%20(Factory%20New)"],
"AWP | The Prince" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097680", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097527", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097395", "-", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176097840", "https://steamcommunity.com/market/listings/730/AWP%20%7C%20The%20Prince%20(Factory%20New)"],
"AWP | Desert Hydra" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263304", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263188", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176262824", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263023", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263253", "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Desert%20Hydra%20(Factory%20New)"],

"SG 553 | Hazard Pay" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263229", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263130", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263270", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263228", "https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=176263333", "https://steamcommunity.com/market/listings/730/SG%20553%20%7C%20Hazard%20Pay%20(Factory%20New)"],
"SG 553 | Bulldozer" : ["https://steamcommunity.com/market/itemordershistogram?country=RU&language=russian&currency=5&item_nameid=49742751", "-", "-", "-", "-", "https://steamcommunity.com/market/listings/730/SG%20553%20%7C%20Bulldozer%20(Factory%20New)"],
"SG 553 | Integrale" : ["-", "-", "-", "-", "-", ""],
"SG 553 | Tornado" : ["-", "-", "-", "-", "-", ""],
"SG 553 | Hypnotic" : ["-", "-", "-", "-", "-", ""],




                         }



# "M4A4 | Daybreak" : ["-", "-", "-", "-", "-", "-"],